#pragma once

#include <string>
#include <unordered_map>

namespace utilities {

    inline std::string get_key_name(int key_code)
    {
        static const std::unordered_map<int, std::string> key_names = {
            { 0x01, "LMB" },
            { 0x02, "RMB" },
            { 0x03, "Cancel" },
            { 0x04, "MMB" },
            { 0x05, "X1" },
            { 0x06, "X2" },
            { 0x08, "Back" },
            { 0x09, "Tab" },
            { 0x0C, "Clear" },
            { 0x0D, "Enter" },
            { 0x10, "Shift" },
            { 0x11, "Ctrl" },
            { 0x12, "Alt" },
            { 0x13, "Pause" },
            { 0x14, "Caps" },
            { 0x1B, "Esc" },
            { 0x20, "Space" },
            { 0x21, "PgUp" },
            { 0x22, "PgDn" },
            { 0x23, "End" },
            { 0x24, "Home" },
            { 0x25, "Left" },
            { 0x26, "Up" },
            { 0x27, "Right" },
            { 0x28, "Down" },
            { 0x29, "Select" },
            { 0x2A, "Print" },
            { 0x2B, "Execute" },
            { 0x2C, "PrtSc" },
            { 0x2D, "Insert" },
            { 0x2E, "Delete" },
            { 0x2F, "Help" },
            { 0x30, "0" },
            { 0x31, "1" },
            { 0x32, "2" },
            { 0x33, "3" },
            { 0x34, "4" },
            { 0x35, "5" },
            { 0x36, "6" },
            { 0x37, "7" },
            { 0x38, "8" },
            { 0x39, "9" },
            { 0x41, "A" },
            { 0x42, "B" },
            { 0x43, "C" },
            { 0x44, "D" },
            { 0x45, "E" },
            { 0x46, "F" },
            { 0x47, "G" },
            { 0x48, "H" },
            { 0x49, "I" },
            { 0x4A, "J" },
            { 0x4B, "K" },
            { 0x4C, "L" },
            { 0x4D, "M" },
            { 0x4E, "N" },
            { 0x4F, "O" },
            { 0x50, "P" },
            { 0x51, "Q" },
            { 0x52, "R" },
            { 0x53, "S" },
            { 0x54, "T" },
            { 0x55, "U" },
            { 0x56, "V" },
            { 0x57, "W" },
            { 0x58, "X" },
            { 0x59, "Y" },
            { 0x5A, "Z" },
            { 0x5B, "LWin" },     
            { 0x5C, "RWin" },     
            { 0x5D, "Apps" },     
            { 0x60, "Numpad0" },  
            { 0x61, "Numpad1" },  
            { 0x62, "Numpad2" },  
            { 0x63, "Numpad3" },  
            { 0x64, "Numpad4" },  
            { 0x65, "Numpad5" },  
            { 0x66, "Numpad6" },  
            { 0x67, "Numpad7" },  
            { 0x68, "Numpad8" },
            { 0x69, "Numpad9" },  
            { 0x6A, "Multiply" }, 
            { 0x6B, "Add" },      
            { 0x6C, "Separator" },
            { 0x6D, "Subtract" }, 
            { 0x6E, "Decimal" },  
            { 0x6F, "Divide" },   
            { 0x70, "F1" },       
            { 0x71, "F2" },       
            { 0x72, "F3" },       
            { 0x73, "F4" },       
            { 0x74, "F5" },
            { 0x75, "F6" },       
            { 0x76, "F7" },
            { 0x77, "F8" },       
            { 0x78, "F9" },       
            { 0x79, "F10" },      
            { 0x7A, "F11" },      
            { 0x7B, "F12" },      
            { 0x90, "NumLock" },  
            { 0x91, "Scroll" },   
            { 0xA0, "LShift" },    
            { 0xA1, "RShift" },   
            { 0xA2, "LCtrl" },    
            { 0xA3, "RCtrl" },    
            { 0xA4, "LAlt" },     
            { 0xA5, "RAlt" },     
        };

        auto it = key_names.find(key_code);
        if (it != key_names.end())
            return it->second;
        
        return std::to_string(key_code);
    }

    inline bool is_key_valid(int key_code)
    {
        return key_code >= 0x01 && key_code <= 0xA5;
    }

}
